// Generated by https://quicktype.io

export interface RegisterResponse {
    id:        string;
    username:  string;
    email:     string;
    avatar:    string;
    roles:     string[];
    createdAt: string;
}
