// Generated by https://quicktype.io

export interface UserDetailsResponse {
    username:         string;
    email:            string;
    avatar:           string;
    horasDisponibles: number;
    createdAt:        null;
}
