// Generated by https://quicktype.io

export interface LoginResponse {
    id:       string;
    username: string;
    email:    string;
    avatar:   string;
    roles:    string[];
    token:    string;
}
